[package]
name = "libsignal-protocol-rust"
version = "0.1.0"
authors = ["Ehren Kret <ehren@signal.org>", "Jack Lloyd <jack@signal.org>"]
edition = "2018"
license = "GPL-3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aes = "0.5"
arrayref = "0.3.6"
block-modes = "0.6"
bytes = "0.5"
curve25519-dalek = "3.0.0"
hmac = "0.9.0"
prost = "0.6"
rand = "0.7.3"
sha2 = "0.9"
subtle = "2.2.3"
x25519-dalek = "1.0"

[features]
default = ["u64_backend"]
u32_backend = ["curve25519-dalek/u32_backend"]
u64_backend = ["curve25519-dalek/u64_backend"]
simd_backend = ["curve25519-dalek/simd_backend"]
nightly = ["curve25519-dalek/nightly"]

[dev-dependencies]
hex = "0.4"
criterion = "0.3"

[build-dependencies]
prost-build = "0.6"

[[bench]]
name = "session"
harness = false
