[package]
name = "libsignal-protocol-rust"
version = "0.1.0"
authors = ["Ehren Kret <ehren@signal.org>", "Jack Lloyd <jack@signal.org>"]
edition = "2018"
license = "GPL-3"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrayref = "0.3.6"
bytes = "0.5"
curve25519-dalek = "2.0.0"
hmac = "0.7.1"
prost = "0.6"
rand = "0.7.3"
sha2 = "0.8.1"
subtle = "2.2.2"
x25519-dalek = "0.6.0"
aes = "0.4"
block-modes = "0.5"

[dev-dependencies]
hex = "0.4"

[build-dependencies]
prost-build = "0.6"
